# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
- id: kubectx
  main: ./cmd/kubectx
  binary: kubectx
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
    - ppc64le
  goarm: [6, 7]
- id: kubens
  main: ./cmd/kubens
  binary: kubens
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
    - ppc64le
  goarm: [6, 7]
archives:
- name_template: |-
    kubectx_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    {{- with .Arm -}}
      {{- if (eq . "6") -}}hf
      {{- else -}}v{{- . -}}
      {{- end -}}
    {{- end -}}
  builds:
    - kubectx
    - kubens
  replacements:
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files: ["LICENSE"]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
brews:
- github:
    owner: caarlos0
    name: homebrew-tap
  folder: Formula
  description: 'kubectx and kubens are power tools for kubectl'
  homepage: https://kubectx.dev
  install: |-
    bin.install "kubens"
    bin.install "kubectx"
    bash_completion.install "completion/kubectx.bash" => "kubectx"
    bash_completion.install "completion/kubens.bash" => "kubens"
    zsh_completion.install "completion/kubectx.zsh" => "_kubectx"
    zsh_completion.install "completion/kubens.zsh" => "_kubens"
    fish_completion.install "completion/kubectx.fish"
    fish_completion.install "completion/kubens.fish"
